import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Flipped } from 'react-flip-toolkit';
import { LandingHero } from '@/components/Hero';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <LandingHero/>

      <main className={styles.main}>
        <Flipped flipId="latest-writing-heading" spring="noWobble" translate>
        {(flippedProps) => (
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui deserunt vel saepe laudantium eum odio maxime quis, quia officia veniam hic quas tempora eos placeat reiciendis eius quos itaque fuga!</div>
          )}
        </Flipped>
      </main>
    </>
  )
}
